[tox]
isolated_build = True
envlist = py39,py310,py311,linting

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311

[testenv:linting]
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure

[testenv]
deps =
    black
    flake8
    isort
    mccabe
#    pylint
    pytest
commands =
    black --check .
    isort --check .
    flake8 .
#    pylint distgfs.py
    pytest .
